Repository cms-gem-daq-project/gem-light-dqm, pull requests merged in 2019-03, with the labels that each got.

#30 New Feature: Adding Functionality for Multiple AMC's
  dqm-root/src/common/GEB_histogram.cxx
  dqm-root/src/common/gemTreeReader.cxx
Labels: PR: reviewed-approved, Priority: Medium, Status: Review Needed, Type: Enhancement

#31 Hot Fix: Resolved std::string vs const char * issue
  dqm-root/src/common/gemTreeReader.cxx
Labels: PR: reviewed-approved, Priority: High, Type: Bugfix, Type: Maintenance

#33 Stripping the histograms to reduce memory consumption
  dqm-root/src/common/AMC13_histogram.cxx
  dqm-root/src/common/AMC_histogram.cxx
  dqm-root/src/common/GEB_histogram.cxx
  dqm-root/src/common/VFAT_histogram.cxx
  dqm-root/src/common/dqmMain.cxx
  dqm-root/src/common/gemTreeReader.cxx
Labels: Priority: Critical, Status: Review Needed, Type: Bugfix, Type: Enhancement, Type: Maintenance

#34 Restoring 2D Latency Scan Histogram to VFAT_Histograms
  dqm-root/src/common/VFAT_histogram.cxx
Labels: PR: reviewed-approved, Priority: High, Status: Review Needed, Type: Bugfix, Type: Maintenance
